blank_issues_enabled: false
contact_links:
  - name: UnQBase related issues
    url: https://github.com/UnQBase/UnQBase.new/issues/new/choose
    about: Report issues related to UnQBase (not UnQBase.diy)
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other UnQBase.diy users.
